### ISSUE TITLE
Library ignores the capitalized `map_D` in material file.

### ISSUE THREAD

**Issue by jqly** [tinyobjloader/tinyobjloader#185]
I came across with a material containing `map_D`(note the capitalized `D`). I wander if the library could identify such words(making them all lower cases, for example). For now, it seems that the library just ignore this.

**Comment by syoyo** [comment]
Currently tinyobjloader distinguish upper and lower case strings. Thus `map_d` is supported but `map_D` is not supported. 

PR for lowering string is welcome.
