### ISSUE TITLE
GitHub credentials are causing Travis to fail in release step

### ISSUE THREAD

**Issue by paulmelnikow** [tinyobjloader/tinyobjloader#255]
I noticed the release is failing in Travis due to bad credentials:

```
/home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.6.2/lib/octokit/connection.rb:19:in `get'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/octokit-4.6.2/lib/octokit/client/users.rb:34:in `user'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-releases-1.10.14/lib/dpl/provider/releases.rb:58:in `user'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-releases-1.10.14/lib/dpl/provider/releases.rb:83:in `setup_auth'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-releases-1.10.14/lib/dpl/provider/releases.rb:87:in `check_auth'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.14/lib/dpl/provider.rb:187:in `block in deploy'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.14/lib/dpl/cli.rb:41:in `fold'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.14/lib/dpl/provider.rb:186:in `deploy'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.14/lib/dpl/cli.rb:32:in `run'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.14/lib/dpl/cli.rb:7:in `run'

	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.14/bin/dpl:5:in `<top (required)>'

	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `load'

	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `<main>'

failed to deploy
```

I guess this is where it's trying to publish to?

https://bintray.com/syoyo/tinyobjloader

It looks like there hasn't been a release there since 2016. Would it make sense to turn off the Bintray publishing, to get the build back to green? Or would it be better to fix the GitHub credentials?

I'm also not quite sure why the release is running for every architecture. It seems like it's only intended to run for one of the items in the build matrix, the one with `DEPLOY_BUILD=1`.

**Comment by syoyo** [comment]
I forgot why I made this. Probably for passing build artifact on Bintray to code analysis services or something. 

I think I can remove this feature since this is not used anymore.

**Comment by syoyo** [comment]
Apparently, PR https://github.com/syoyo/tinyobjloader/pull/254 solved this issue.

**Comment by paulmelnikow** [comment]
I'm not sure that's true. It doesn't run on PR's, only merges, and I think Travis may need to be set up again after the repo move.

**Comment by paulmelnikow** [comment]
Ahh, I think the Bintray deployment is for Conan.

**Comment by syoyo** [comment]
It was my test for releasing CI build artifact to Bintray  > https://qiita.com/syoyo/items/e018214265fdc02c39c0 (in Japanese)

So, it should now remove this redundant step from Travis script.

**Comment by paulmelnikow** [comment]
I think I'm not quite clear about this. Should something be removed from the Travis config? Could you make the change?

**Comment by syoyo** [comment]
It should be ok to remove bintray build step and deprecate conan build. I think no one is using bintray and conan. Also it is not a recommended way to use tinyobjloader(since its a header-only library)

I will work on removing bintray build step at some point.

**Comment by syoyo** [comment]
Removed bintray support  https://github.com/tinyobjloader/tinyobjloader/pull/317 so closing the issue.
