### ISSUE TITLE
Suggestion: Use squashed commits

### ISSUE THREAD

**Issue by paulmelnikow** [tinyobjloader/tinyobjloader#258]
Hi, I wanted to suggest setting this repo to allow only squash commits via the merge button. It means that when a PR is merged, the changes get combined into a single commit that's applied to master. This results in a straight-line history which in my experience is much easier to follow. You can combine or reword the commit message the time of merging.

It's under Settings:

<img width="799" alt="Screen Shot 2020-02-20 at 12 16 37 PM" src="https://user-images.githubusercontent.com/1487036/74960819-0086d100-53db-11ea-8859-23af69d1d69a.png">

What do you think @syoyo?

**Comment by syoyo** [comment]
@paulmelnikow Oh, I didn't know such feature is available in Github. Yes, we've better to do it!

**Comment by paulmelnikow** [comment]
Cool! Can you make the change? Or you could make me a repo admin, then I could change it myself.

**Comment by syoyo** [comment]
@paulmelnikow Set `Member` privilege to `admin`, so now you can change setting by yourself!

**Comment by paulmelnikow** [comment]
And, done! Thanks :)
