### ISSUE TITLE
C++20 Incompatible Change

### ISSUE THREAD

**Issue by bjadamson** [tinyobjloader/tinyobjloader#259]
I just pulled down the latest version of clang and am getting a ton of warnings from tinyobj. Looks like this was recently implemented in LLVM [here](https://reviews.llvm.org/D74103) based on this paper [here](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1766r1.html).

I realize the README.md says this is a C++03 library, but I'm wondering if you think tinyobj should adopt to this change.

> anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here

With the latest version of clang I compiled I'm getting the following warnings:

> ./external/tinyobj/tiny_obj_loader.h:157:15: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
typedef struct {
              ^
               texture_option_t
../external/tinyobj/tiny_obj_loader.h:157:9: note: type is not C-compatible due to this member declaration
typedef struct {
        ^~~~~~
../external/tinyobj/tiny_obj_loader.h:175:3: note: type is given name 'texture_option_t' for linkage purposes by this typedef declaration
} texture_option_t;
  ^
../external/tinyobj/tiny_obj_loader.h:322:15: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
typedef struct {
              ^
               tag_t
../external/tinyobj/tiny_obj_loader.h:322:9: note: type is not C-compatible due to this member declaration
typedef struct {
        ^~~~~~
../external/tinyobj/tiny_obj_loader.h:328:3: note: type is given name 'tag_t' for linkage purposes by this typedef declaration
} tag_t;
  ^
../external/tinyobj/tiny_obj_loader.h:338:15: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
typedef struct {
              ^
               mesh_t
../external/tinyobj/tiny_obj_loader.h:338:9: note: type is not C-compatible due to this member declaration
typedef struct {
        ^~~~~~
../external/tinyobj/tiny_obj_loader.h:349:3: note: type is given name 'mesh_t' for linkage purposes by this typedef declaration
} mesh_t;
  ^
../external/tinyobj/tiny_obj_loader.h:355:15: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
typedef struct {
              ^
               lines_t
../external/tinyobj/tiny_obj_loader.h:355:9: note: type is not C-compatible due to this member declaration
typedef struct {
        ^~~~~~
../external/tinyobj/tiny_obj_loader.h:359:3: note: type is given name 'lines_t' for linkage purposes by this typedef declaration
} lines_t;
  ^
../external/tinyobj/tiny_obj_loader.h:361:15: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
typedef struct {
              ^
               points_t
../external/tinyobj/tiny_obj_loader.h:361:9: note: type is not C-compatible due to this member declaration
typedef struct {
        ^~~~~~
../external/tinyobj/tiny_obj_loader.h:363:3: note: type is given name 'points_t' for linkage purposes by this typedef declaration
} points_t;
  ^
../external/tinyobj/tiny_obj_loader.h:365:15: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
typedef struct {
              ^
               shape_t
../external/tinyobj/tiny_obj_loader.h:365:9: note: type is not C-compatible due to this member declaration
typedef struct {
        ^~~~~~
../external/tinyobj/tiny_obj_loader.h:370:3: note: type is given name 'shape_t' for linkage purposes by this typedef declaration
} shape_t;

Here's the commit message associated with the commit here:
Commit message here

> - Clang now implements a restriction on giving non-C-compatible anonymous
>   structs a typedef name for linkage purposes, as described in C++ committee
>   paper `P1766R1 <http://wg21.link/p1766r1>`. This paper was adopted by the
>   C++ committee as a Defect Report resolution, so it is applied retroactively
>   to all C++ standard versions. This affects code such as:
> 
>   .. code-block:: c++
> 
>     typedef struct {
>       int f() { return 0; }
>     } S;
> 
>   Previous versions of Clang rejected some constructs of this form
>   (specifically, where the linkage of the type happened to be computed
>   before the parser reached the typedef name); those cases are still rejected
>   in Clang 11.  In addition, cases that previous versions of Clang did not
>   reject now produce an extension warning. This warning can be disabled with
>   the warning flag ``-Wno-non-c-typedef-for-linkage``.
> 
>   Affected code should be updated to provide a tag name for the anonymous
>   struct:
> 
>   .. code-block:: c++
> 
>     struct S {
>       int f() { return 0; }
>     };
> 
>   If the code is shared with a C compilation (for example, if the parts that
>   are not C-compatible are guarded with ``#ifdef __cplusplus``), the typedef
>   declaration should be retained, but a tag name should still be provided:
> 
>   .. code-block:: c++
> 
>     typedef struct S {
>       int f() { return 0; }
>     } S;

**Comment by syoyo** [comment]
> I just pulled down the latest version of clang and am getting a ton of warnings from tinyobj. 

Oh! good to know.

> I realize the README.md says this is a C++03 library

Yes, we still need to stick into C++03. I think  we can simply rewrite struct definition with

```
struct S {
int f() { return 0; }
};
```

it looks it is ok for C++03 compiler(tested with clang and gcc with `-std=c++03`).

`typedef struct S`  gets a warning with `-std=c++03`

**Comment by paulmelnikow** [comment]
Can we add a compile step using C++20 to the build matrix? Maybe in Travis is the easiest place for now?

**Comment by syoyo** [comment]
C++20 support in clang is too new and I'm not sure there is a prebuilt clang which supports C++20. We may better to wait until Clang11 is out(which would support C++20)

**Comment by bjadamson** [comment]
Should I make a pull request? How would you like to proceed?

**Comment by syoyo** [comment]
@bjadamson Yes, PR is much appreciated!

**Comment by bjadamson** [comment]
PR sent! Quick question, what is this idiom used for? Is there some benefit over a plain struct definition I'm not aware of? Thanks!

```c
typedef struct { ...} the_struct;
```

**Comment by syoyo** [comment]
> typedef struct { ...} the_struct;

Not sure. Probably this syntax was valid and common for old C++98 or C++03 era.

**Comment by syoyo** [comment]
> PR sent!

@bjadamson Merged! So this issue should be ready to close.
