### ISSUE TITLE
mesh_t does not have a member named numpy_num_face_vertices

### ISSUE THREAD

**Issue by ParikaGoel** [tinyobjloader/tinyobjloader#265]
I have installed tinyobjloader using pip which installs 0.1 version. 
It recognizes only indices member of the mesh structure

My code snippet: 

def read_obj(filename):
    reader = tinyobjloader.ObjReader()
    ret = reader.ParseFromFile(filename)

    if ret == False:
        print("Warn:", reader.Warning())
        pint("Err:", reader.Error())
        print("Failed to load : ", filename)

        sys.exit(-1)

    attrib = reader.GetAttrib()
    shapes = reader.GetShapes()

    for shape in shapes:
        print(len(shape.mesh.numpy_num_face_vertices))

**Comment by paulmelnikow** [comment]
The latest release is a prerelease so it won’t be installed unless you ask for it. Please try `pip install==2.0.0rc5`.

**Comment by ParikaGoel** [comment]
Thank you for the reply
I upgraded the pip package, but I still can not access numpy_num_face_vertices
Though, I am able to access num_face_vertices now

**Comment by syoyo** [comment]
@ParikaGoel You need to access `numpy_num_face_vertices` as a method.  

https://github.com/tinyobjloader/tinyobjloader/blob/c255ab333f7a8e0c8ab5c96468cab2f665bc2ee9/python/sample.py#L77

**Comment by ParikaGoel** [comment]
Thank you for your reply. It works now
