### ISSUE TITLE
How can I get the color information for each vertex

### ISSUE THREAD

**Issue by ParikaGoel** [tinyobjloader/tinyobjloader#266]
I want to convert my obj file to ply file. So, I am reading the vertex and face information from obj file and writing it to ply file. But I don't know how can I get the color information for each vertex.

**Comment by syoyo** [comment]
https://github.com/tinyobjloader/tinyobjloader/blob/c255ab333f7a8e0c8ab5c96468cab2f665bc2ee9/tiny_obj_loader.h#L384
