### ISSUE TITLE
Pip installation failing on windows

### ISSUE THREAD

**Issue by brupelo** [tinyobjloader/tinyobjloader#273]
**Requirements:**

Python version: '3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]'
OS: win7 - x64
Compiler: Visual studio 2015 or 2017

**Steps to reproduce:**

1. Open a visual studio command prompt (x86)
2. Activate your virtualenv
3. `pip install tinyobjloader`

**Problem**

Below you'll see the whole output when running 3)

    Collecting tinyobjloader
      Using cached tinyobjloader-0.1.tar.gz (3.1 kB)
    Building wheels for collected packages: tinyobjloader
      Building wheel for tinyobjloader (setup.py): started
      Building wheel for tinyobjloader (setup.py): finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'D:\virtual_envs\py382_32\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\KneDa\\AppData\\Local\\Temp\\pip-install-7zzqd0rc\\tinyobjloader\\setup.py'"'"'; __file__='"'"'C:\\Users\\KneDa\\AppData\\Local\\Temp\\pip-install-7zzqd0rc\\tinyobjloader\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\KneDa\AppData\Local\Temp\pip-wheel-4sz5npvv'
           cwd: C:\Users\KneDa\AppData\Local\Temp\pip-install-7zzqd0rc\tinyobjloader\
      Complete output (12 lines):
      running bdist_wheel
      running build
      running build_ext
      building 'tinyobjloader' extension
      creating build
      creating build\temp.win32-3.8
      creating build\temp.win32-3.8\Release
      C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../ -I../pybind11/include -ID:\virtual_envs\py382_32\include -Id:\software\python\3.8.2\include -Id:\software\python\3.8.2\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tpbindings.cc /Fobuild\temp.win32-3.8\Release\bindings.obj -std=c++11
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      bindings.cc
      bindings.cc(1): fatal error C1083: Cannot open include file: 'pybind11/pybind11.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
      ----------------------------------------
      ERROR: Failed building wheel for tinyobjloader
      Running setup.py clean for tinyobjloader
    Failed to build tinyobjloader
    Installing collected packages: tinyobjloader
        Running setup.py install for tinyobjloader: started
        Running setup.py install for tinyobjloader: finished with status 'error'
        ERROR: Command errored out with exit status 1:
         command: 'D:\virtual_envs\py382_32\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\KneDa\\AppData\\Local\\Temp\\pip-install-7zzqd0rc\\tinyobjloader\\setup.py'"'"'; __file__='"'"'C:\\Users\\KneDa\\AppData\\Local\\Temp\\pip-install-7zzqd0rc\\tinyobjloader\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\KneDa\AppData\Local\Temp\pip-record-h1qpizu_\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\virtual_envs\py382_32\include\site\python3.8\tinyobjloader'
             cwd: C:\Users\KneDa\AppData\Local\Temp\pip-install-7zzqd0rc\tinyobjloader\
        Complete output (12 lines):
        running install
        running build
        running build_ext
        building 'tinyobjloader' extension
        creating build
        creating build\temp.win32-3.8
        creating build\temp.win32-3.8\Release
        C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../ -I../pybind11/include -ID:\virtual_envs\py382_32\include -Id:\software\python\3.8.2\include -Id:\software\python\3.8.2\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tpbindings.cc /Fobuild\temp.win32-3.8\Release\bindings.obj -std=c++11
        cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
        bindings.cc
        bindings.cc(1): fatal error C1083: Cannot open include file: 'pybind11/pybind11.h': No such file or directory
        error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
        ----------------------------------------
    ERROR: Command errored out with exit status 1: 'D:\virtual_envs\py382_32\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\KneDa\\AppData\\Local\\Temp\\pip-install-7zzqd0rc\\tinyobjloader\\setup.py'"'"'; __file__='"'"'C:\\Users\\KneDa\\AppData\\Local\\Temp\\pip-install-7zzqd0rc\\tinyobjloader\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\KneDa\AppData\Local\Temp\pip-record-h1qpizu_\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\virtual_envs\py382_32\include\site\python3.8\tinyobjloader' Check the logs for full command output.

Could you please explain what'd the proper way to create the tinyobjloader wheel to run on py3.8.2 (x86) + windows?

**Comment by paulmelnikow** [comment]
Hi! Have you tried the recent rcs?

**Comment by syoyo** [comment]
> Have you tried the recent rcs? 

@brupelo FYI which means 2.0.0rc5

https://pypi.org/project/tinyobjloader/2.0.0rc5/

**Comment by paulmelnikow** [comment]
(Sorry!  I was on mobile.)

**Comment by brupelo** [comment]
Ok, guys, thanks... I can confirm that version `2.0.0rc5` solved the issue so I guess this issue has become ready.

One additional question (probably offtopic) is that few months ago I was working with an older version of tinyobjloader and I had this chunk of code such as:

```
        for k, v in model["shapes"].items():
            faces.extend(v["indices"][::3])
```

But this has changed in recent versions so... how could i migrate my old code to the new version? I can see right now the new classes look like this:

```
        for shape in shapes:
            log.debug(shape.name)
            log.debug(f"num_indices = {len(shape.mesh.indices)}")
            faces+=shape.mesh.indices
        # vertex data must be `xyzxyzxyz...`
        # normal data must be `xyzxyzxyz...`
        # texcoords data must be `uvuvuv...`
        assert len(attrib.vertices) % 3 == 0
        assert len(attrib.normals) % 3 == 0
        assert len(attrib.texcoords) % 2 == 0


But not sure very well how to extract all triangles from there... Hope you can advice :)

``Thanks!

**Comment by brupelo** [comment]
Forget about my previous question, it was just a matter to review again the docs... although for some reason I'm getting error when trying to read material id's on https://pypi.org/project/tinyobjloader/2.0.0rc5/...

`AttributeError:` 'tinyobjloader.mesh_t' object has no attribute 'material_ids'

But i guess that's a different issue, so I'm closing this one

**Comment by brupelo** [comment]
Cos let me ask you... why in `https://github.com/tinyobjloader/tinyobjloader/blob/v2.0.0rc5/python/bindings.cc` isn't exposed material_ids?

I'm seeing it exposed in master though :/ ... https://github.com/tinyobjloader/tinyobjloader/blob/master/python/bindings.cc#L148-L154

**Comment by brupelo** [comment]
Anyway... i've decided to switch from https://pypi.org/project/tinyobjloader/2.0.0rc5/ to master and it seems it'll compile ok now with visual studio 2015...That way i can have `matrial_ids` exposed... really confusing why in rc5 wasn't exposed though... :/

**Comment by syoyo** [comment]
We can simply need re-tag `master` to expose it.

@paulmelnikow Tagging `master` to `2.0.0-rc6` or something then push it to github will sync pip repo's tag"

**Comment by paulmelnikow** [comment]
Sorry, just seeing this.

There's also version number checked in, I think in `setup.py`, which has to be updated before the tagging happens. As of right now, the publish to PyPI happens is a separate step, which generates an artifact and pushes it to their servers.

Would you like me to do that?

**Comment by syoyo** [comment]
@paulmelnikow I have updated version number in `setup.py`

https://github.com/tinyobjloader/tinyobjloader/commit/df61facbd7e69981268787a969f583cacdda7d0f

 and tagged it `v2.0.0rc6`, then pushed it but nothing happens in PyPI repo.

It looks something is not working well in uploading artifacts from cibuildwheel on azure-pipelines?

**Comment by paulmelnikow** [comment]
The other steps are to run:

```sh
cd python
rm -rf dist/
python setup.py sdist # This creates a source distribution, which cibuildwheel does not
# Download all the build artifacts from cibuildwheel on the tagged commit and add them to dist/
twine upload dist/*
```

We should write this up!

**Comment by syoyo** [comment]
@paulmelnikow I see

We can automatically upload wheels using twine: https://github.com/joerick/cibuildwheel-autopypi-example

Recently I have setup this on Travis for another project `pytinyexr`:

https://github.com/syoyo/PyEXR/blob/master/.travis.yml

I think we can do same thing for Azure Pipeline. I'll try it out.

**Comment by paulmelnikow** [comment]
Sounds good. Should we track this in a new issue?

**Comment by syoyo** [comment]
@paulmelnikow I have added section to this issue: https://github.com/tinyobjloader/tinyobjloader/issues/257 

Setting twine for Azure pipeline seems difficult to manage,  so I am now trying to setup Travis CI.

**Comment by paulmelnikow** [comment]
Since it requires all the platformed build artifacts from Azure Pipelines I think running it in Travis could be tricky.

**Comment by syoyo** [comment]
@paulmelnikow I have setup Azure Pipeline to automate cibuildwheel + twine upload to PyPI for each tag commit.

https://github.com/tinyobjloader/tinyobjloader/blob/master/azure-pipelines.yml

https://pypi.org/project/tinyobjloader/2.0.0rc6/#files

Now once you push a tag(e.g. `v2.0.1`), binary and source are automatically uploaded to PyPI.

@paulmelnikow See how to bump version here:

https://github.com/tinyobjloader/tinyobjloader#how-to-bump-versionfor-developer
