### ISSUE TITLE
Tinyobjloader is used in metal ray tracer

### ISSUE THREAD

**Issue by sergeyreznik** [tinyobjloader/tinyobjloader#278]
Hi!
I just want to let you know that I’m using tinyobjloader in my ray tracing project 
https://github.com/sergeyreznik/metal-ray-tracer
It would be awesome to appear in projects list :)

**Comment by syoyo** [comment]
Awesome!

Will soon add to the list.

BTW, URL for tinyobjloader has been changed to https://github.com/tinyobjloader/tinyobjloader/
(Now hosted at tinyobjloader organizaton)

Could you please update the URL for tinyobjloader in your metal ray tracer document? e.g. at https://sergeyreznik.github.io/metal-ray-tracer/part-2/index.html

**Comment by syoyo** [comment]
Added to the list in this commit: https://github.com/tinyobjloader/tinyobjloader/commit/cff52cd9eafac54cf8bbe3ca7da8219122acbf5d

**Comment by sergeyreznik** [comment]
Thank you!
I've updated links - both in part 2 and index
