### ISSUE TITLE
Per face material not working?

### ISSUE THREAD

**Issue by vintagepc** [tinyobjloader/tinyobjloader#279]
I'm encountering some issues getting the rendering correct with objects that have per-face material. It's entirely possible I'm doing something wrong, but I've gone off the reference "viewer" code and while I'm currently using 1.0.6 in the project, I've tried the latest 2.0 RC and it did not appear to correct the issue. 

Can you offer some guidance, or is this a known issue?

How the object looks in a third-party tool (GLC_Player)

![image](https://user-images.githubusercontent.com/53943260/89090093-aff2a700-d36e-11ea-9f12-b7d66b8ce5a6.png)

How it renders when using tinyobjloader:
![image](https://user-images.githubusercontent.com/53943260/89090124-d87aa100-d36e-11ea-8071-0dc9829e9d28.png)

Here is the model file:
[model.zip](https://github.com/tinyobjloader/tinyobjloader/files/5009488/model.zip)

Thanks in advance!

**Comment by syoyo** [comment]
Please use the issue template to describe your issue

**Comment by vintagepc** [comment]
I will if it continues to be an issue. I'm reviewing things now and it looks to be an issue with the conversion from using color vertices to materials after enabling lighting, on my end.

**Comment by syoyo** [comment]
@vintagepc I see. I have added per-face material id visualization to nanort gui example(load .obj using tinyobjloader and render it using CPU ray tracing). https://github.com/lighttransport/nanort/tree/master/examples/gui

This would help to investigate the issue. It also supports visualizing vertex color of .obj mesh.

**Comment by vintagepc** [comment]
Oh, cool - I'll have to look at that, thanks.

**Comment by vintagepc** [comment]
Resolved it was indeed on my end; I had to update the loading code to create a new drawable object if the material changes within the shape.
