### ISSUE TITLE
RMA texture support

### ISSUE THREAD

**Issue by astrand130** [tinyobjloader/tinyobjloader#282]
Feature Request:

Microsoft's DirectXMesh tool supports an OBJ extension that implements GLTF style Roughness-Metal-AO maps. Native support for this kind of texture in this library would be a welcome addition. https://github.com/microsoft/DirectXMesh/pull/39

Thank You!

**Comment by syoyo** [comment]
You should use issue template to file an issue: https://github.com/tinyobjloader/tinyobjloader/issues/new/choose

**Comment by astrand130** [comment]
> You should use issue template to file an issue: https://github.com/tinyobjloader/tinyobjloader/issues/new/choose

I tried but there is no template for a feature request. Sorry.
