### ISSUE TITLE
pybind11 available as tags in repo

### ISSUE THREAD

**Issue by madebr** [tinyobjloader/tinyobjloader#286]
**Describe the issue**
pybind11 is available as versioned tags in this repo.

[Our automatic update checker for the recipes in conan-center-index](https://qchateau.github.io/conan-center-bot/#/updatable) falsely detected a new 1.7 release for tinyobjloader.

**To Reproduce**

https://github.com/tinyobjloader/tinyobjloader/tree/v1.1
https://github.com/tinyobjloader/tinyobjloader/tree/v1.2
https://github.com/tinyobjloader/tinyobjloader/tree/v1.3
https://github.com/tinyobjloader/tinyobjloader/tree/v1.4
https://github.com/tinyobjloader/tinyobjloader/tree/v1.4.1
https://github.com/tinyobjloader/tinyobjloader/tree/v1.5
https://github.com/tinyobjloader/tinyobjloader/tree/v1.7

**Expected behavior**
I think these should not be tagged here, or at least be prepended with e.g. pybind11-.

**Comment by syoyo** [comment]
@madebr Nice! > Our automatic update checker

pybind11 tags are included in the repo for some reason. 

https://github.com/tinyobjloader/tinyobjloader/issues/212

I need to delete tags you listed. Let me give some time to review and clean it.

**Comment by madebr** [comment]
Sorry about opening a second issue about this.
I didn't search hard enough.

Thanks for maintaining tinyobjloader btw

**Comment by syoyo** [comment]
@madebr Invalid tags are now deleted. Thank you for reporting!
