### ISSUE TITLE
Talos Security Advisory for tinyobjloader (TALOS-2020-1212)

### ISSUE THREAD

**Issue by CiscoTalos** [tinyobjloader/tinyobjloader#287]
The Cisco Talos team found a security vulnerability affecting tinyobjloader. As this is a sensitive security issue, please provide a method where the issue can be tagged as security issue and not public. Additionally, we can correspond via email if you have a contact handling vulnerabilities (if contact has PGP, please also include).

For further information about the Cisco Vendor Vulnerability Reporting and Disclosure Policy please refer to this document which also links to our public PGP key. https://tools.cisco.com/security/center/resources/vendor_vulnerability_policy.html

**Comment by syoyo** [comment]
You should use issue template to report an issue with reproducible procedure https://github.com/tinyobjloader/tinyobjloader/issues/new?assignees=&labels=&template=issue-report.md&title=

**Comment by paulmelnikow** [comment]
Hi @syoyo it sounds like they're wanting to disclose this in a non-public way. I'm happy to converse with them over email. Maybe we should ask them to email us both?

**Comment by syoyo** [comment]
@paulmelnikow Things should be public since tinyobjloader is not intended to be used in security-critical application.

**Comment by CiscoTalos** [comment]
This isn't spam, or email is vulndev@cisco.com if you'd prefer to send us an email.

**Comment by paulmelnikow** [comment]
@syoyo Understood. I maintain a couple security-sensitive applications which use it. I understand that securing tinyobjloader might not be necessary for you, though it is for me. Would you be okay with me taking responsibility for security?

**Comment by syoyo** [comment]
@paulmelnikow Yeah! You have full control of security-related issues/tasks!

@CiscoTalos Good to know its not a spam account 🎉

**Comment by paulmelnikow** [comment]
Hi @CiscoTalos, please contact me at the address on my GitHub profile. Thank you for reaching out.

**Comment by CiscoTalos** [comment]
Thanks
