### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by heliobatimarqui** [tinyobjloader/tinyobjloader#291]
Shouldn't ObjReader return a scene/mesh object? 

I understand that a reader is one thing that has it's own state (in fact you set a ObjReaderConfig for it) and that it should then create an object that can be used by the user. Tying up both in one thing feels a little bit counter intuitive. 

Thank you.

**Comment by syoyo** [comment]
You need to describe the issue in detail using the template

https://github.com/tinyobjloader/tinyobjloader/issues/new?assignees=&labels=&template=issue-report.md&title=
