### ISSUE TITLE
Problem loading .obj just because vertice values are (little) larger.

### ISSUE THREAD

**Issue by HakkaTjakka** [tinyobjloader/tinyobjloader#293]
Hello, i have described  my problem in a separate repo, i hope one can take a look at it?
I would be very happy..
It is an issue when loading a .obj file where only the vertices values are higher (offset on X and Z axis)

Tia.

https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h

 - Codeblocks IDE
 - Version tiny_obj_loader.h: Latest from this repo.
 - OS: Windows 10 pro 64 bit
 - Compiler  x86_64-w64-mingw32

**Comment by syoyo** [comment]
You should follow the issue template to file an issue.
