### ISSUE TITLE
Trying again...

### ISSUE THREAD

**Issue by HakkaTjakka** [tinyobjloader/tinyobjloader#294]
**Describe the issue**

# My error report on tiny_obj_loader.h

Hello dear programmers.

I'm using tiny obj loader for a while, and now i'm having some problems...

I have 2 same objects, one is shifted on the X and Z axis. So they have higher values.

Other programs load and show both used objects correct, however loading them with tiny obj loader gives different results.

I don't know what/if i'm doing (something) wrong, like if the .obj files are incorrect format. Or i use wrong compiler/linker(settings).

(i'm using different materials with corresponding faces, on a shared vertices array, where the faces are quats)

Or if there is a bug somewhere. I will try to explain.

I've putted all the files screenshots and info in this 'error report', hoping to make my problem clear...

I have two .obj files.

1) objects_LOW_VALUES\r.28.18.obj

	mtllib concrete.mtl

	v 0.0 0.0 0.0

	v 0.0 1.0 0.0

	v 0.0 0.0 1.0

	v 0.0 1.0 1.0

	v 0.0 0.0 2.0

	v 0.0 1.0 2.0

	(etc...)

2) objects_HIGH_VALUES\r.28.18.obj

	mtllib concrete.mtl

	v 14336.0 0.0 9216.0

	v 14336.0 1.0 9216.0

	v 14336.0 0.0 9217.0

	v 14336.0 1.0 9217.0

	v 14336.0 0.0 9218.0

	v 14336.0 1.0 9218.0

	(etc...)

In the second an offset of X=14336 Y=0 Z=9216 is applied. So al the vertices X and Z coords. are some higher. 
They should fit inside a 32 bit float, i think.

I noticed 'gaps' in the object when loaded with the higher values. (See: HIGH_VALUES_TINY_OBJ.JPG)
(https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/blob/main/HIGH_VALUES_TINY_OBJ.JPG)

However loading the object with a standard viewer shows it correct. (See: HIGH_VALUES.JPG)
(https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/blob/main/HIGH_VALUES.JPG)

When loading the higher values and subtracting the offset AFTER loading with tiny_obj, i created the file: FACES_HIGH_VALUES_ADAPTED.TXT
(https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/blob/main/FACES_HIGH_VALUES_ADAPTED.zip)

So you can compare it with the FACES_LOW_VALUES.TXT, they should be the same.
(https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/blob/main/FACES_LOW_VALUES.zip)
(Zipped because of size)

However multiple batches of 4 faces are missing, showing this (wierd) pattern (screenshots) with a width of 16 between the (same) patterns and other values between the gaps.

The object are like 512 x 512 squares.

I also putted the file FACES_HIGH_VALUES.TXT, showing the loaded FACES, when loaded with higher values, and not adapting them.
(https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/blob/main/FACES_HIGH_VALUES.zip)

As you can see, when loading the object with HIGHER VALUES, gaps show up, because FACES are missing. Not vertices.... (where the higher values are located)

On the lower values i get:

-# of vertices  = 526338  # of normals   = 0  # of colors    = 526338  # of texcoords = 8  # of materials = 16  # of shapes    = 1
shapes[0].mesh.indices.size()=3158016 FACES

On the higher values i get:

-# of vertices  = 526338  # of normals   = 0  # of colors    = 526338  # of texcoords = 8  # of materials = 16  # of shapes    = 1
shapes[0].mesh.indices.size()=2749740 FACES

3158016 - 2749740 = 408276 FACES missing. (Oh my god! ;) )

Below is the code i use after loading the object with tinyobj:

With the higher values i make one file with the original faces: FACES_HIGH_VALUES.TXT
and one with the adapted, FACES_HIGH_VALUES_ADAPTED.TXT, by commenting out the code that subtract the offsets, 
so i can compare the faces of the lower vertices object with the faces of the higher vertices object.
(https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/blob/main/FACES_HIGH_VALUES.zip)
(https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/blob/main/FACES_HIGH_VALUES_ADAPTED.zip)

Because the .obj file i generated has discrete values, i only putted only one 0 behind the decimal dot, but also if i printf the full float with lots of zero's behind the decimal point the behaviour stays the same, some faces are not loaded/handled, somehow.
The two .obj files show exactly the same faces behind the "f ...." flags, so its not in there, i guess, but somehow if the vertices are high values, some faces don't load or show up.
I have not checked inside the tiny_obj_loader.h file yet, i'm using the latest from github, i included it inside this report.
(tinyobjloader-master.zip)
I checked if the issue lies in the use of a decimal point '.' or a decimal comma ',' from the set_locale function, but its no issue in the tinyobj loader. 
I've seen its handled differently for compatibily. (Some c/c++ functions like scanf/printf floats/doubles uses the decimal point settings from the set_locale, and you get/need a '.' or ',' depending on settings in the os).
So i guess its not that.

I haven't debugging any further into the tiny_obj_loader.h yet to check what where my bug is.

I'm wondering: Are my .obj files correct? 
Like i'm using one array of vertices, but 16 arrays of materials, with the faces from the 16 different faces arrays using the ONE array with vertices. (?)
Because the 16 different used materials (with their own texture), are using same shared vertices from the vertices array.
I have not checked what happens if i also use 16 differnt sets of vertice arrays, so you get lots of double vertices, one for every material/faces array. (yet).
But my guess is that if the lower .obj vertice values load correct, it also should load correct with the higher.

So is it the .obj file? Does it has the wrong structure? I tried moving the 'usemtl' and/or the 'o' flag on different locations and/or different order, but no change compared to this output.
Are there funny characters inside the .obj file?
Are the floating point values from the .obj file out of range?
Should i use the TINYOBJLOADER_USE_DOUBLE feature?
Is it in using quads converted to triangles? (Other .obj files with high values using triangles do have not this problem).

So can you help me? What am i doing wrong? (I'm shure its me, but i'm not shure about me being shure its me or its me being shure...)

Here the code i use after i loaded the two different .obj files.

Thanks in advance and have a nice weekend.

Gerard. 

	https://github.com/HakkaTjakka
	gerardwensink@gmail.com
	https://www.facebook.com/Pacman-Graphics-1601114056700700/
	https://www.facebook.com/MinecraftWorldEditor/
	https://www.facebook.com/GoogleEarth3DPostersAndVideos/

	{
	    	float bmin[3], bmax[3];
	    	bmin[0] = bmin[1] = bmin[2] = std::numeric_limits<float>::max();
	    	bmax[0] = bmax[1] = bmax[2] = -std::numeric_limits<float>::max();

		tinyobj::attrib_t attrib;
		std::vector<tinyobj::shape_t> shapes;
		std::vector<tinyobj::material_t> materials
		std::string warn;
		std::string err;

		//given right filename char*, and base_dir std::string

		ret = tinyobj::LoadObj( &attrib, &shapes,
					&materials, &warn,
					&err, filename,
					base_dir.c_str(), true,
					true );

		/*

		// For creating: FACES_HIGH_VALUES_ADAPTED.TXT on directory objects_HIGH_VALUES/r.28.18.obj

		int n_v=(int)(attrib.vertices.size()) / 3;
		for (size_t v = 0; v < n_v; v++) {
			attrib.vertices[3 * v + 0]-=14336;
			attrib.vertices[3 * v + 1]-=0;
			attrib.vertices[3 * v + 2]-=9216;
		}
		*/

		for (size_t s = 0; s < shapes.size(); s++)
		{

			size_t shape_size=shapes[s].mesh.indices.size() / 3;

			printf("shapes[%d].mesh.indices.size()=%d\n",s,shapes[s].mesh.indices.size());

			for (f = 0; f < shape_size; f++)
			{
				tinyobj::index_t idx0 = shapes[s].mesh.indices[3 * f + 0];
				tinyobj::index_t idx1 = shapes[s].mesh.indices[3 * f + 1];
				tinyobj::index_t idx2 = shapes[s].mesh.indices[3 * f + 2];

				float v[3][3];
				for (int k = 0; k < 3; k++)
				{

					int f0 = idx0.vertex_index;             int f1 = idx1.vertex_index;             int f2 = idx2.vertex_index;
					assert(f0 >= 0);                        assert(f1 >= 0);                        assert(f2 >= 0);

					v[0][k] = attrib.vertices[3 * f0 + k];
					v[1][k] = attrib.vertices[3 * f1 + k];
					v[2][k] = attrib.vertices[3 * f2 + k];

					bmin[k] = std::min(v[0][k], bmin[k]);   bmin[k] = std::min(v[1][k], bmin[k]);   bmin[k] = std::min(v[2][k], bmin[k]);
					bmax[k] = std::max(v[0][k], bmax[k]);   bmax[k] = std::max(v[1][k], bmax[k]);   bmax[k] = std::max(v[2][k], bmax[k]);
				}

				// For creating: FACES_LOW_VALUES.TXT, FACES_HIGH_VALUES.TXT, FACES_HIGH_VALUES_ADAPTED.TXT

				sprintf(line,"t %f %f %f - %f %f %f - %f %f %f\n",
					(float)(v[0][0]),(float)(v[0][1]),(float)(v[0][2]),
					(float)(v[1][0]),(float)(v[1][1]),(float)(v[1][2]),
					(float)(v[2][0]),(float)(v[2][1]),(float)(v[2][2])
				);
				printf(line);
			}
		}
	}
	 

**To Reproduce**
1. Compile TinyObjLoader with '...'

Compile:
x86_64-w64-mingw32-g++.exe -O3 -w -std=c++14 -m64 -U__STRICT_ANSI__ -DSFML_STATIC -DFREEGLUT_STATIC -DGLEW_STATIC -Iinclude -Iinclude\cuberite -Icuberite\lib\fmt -Icuberite\lib\mbedtls\include -Icuberite\lib\SQLiteCpp\include -Icuberite\lib\SQLiteCpp\sqlite3 -Icuberite\lib\TCLAP\include -Icuberite\lib\libevent\include -Icuberite\src -Icuberite\lib -Icuberite\lib\jsoncpp\include -Iinclude\MeshLib\core -Ifly\include -Ifly\extlibs -c D:\PACMAN\PACMAN_CUBERITE\src\viewer\viewer_my.cc -o ..\..\obj\PACMAN_CUBERITE\src\viewer\viewer_my.o

Link:
x86_64-w64-mingw32-g++.exe -Llib -o ..\bin\pacman.exe ..\..\obj\PACMAN_CUBERITE\src\Allocator.o ..\..\obj\PACMAN_CUBERITE\src\bitmaps.o ..\..\obj\PACMAN_CUBERITE\src\blending.o ..\..\obj\PACMAN_CUBERITE\src\BLOCKSTATES.o ..\..\obj\PACMAN_CUBERITE\src\commando.o ..\..\obj\PACMAN_CUBERITE\src\convert.o ..\..\obj\PACMAN_CUBERITE\src\exit_program.o ..\..\obj\PACMAN_CUBERITE\src\Fault.o ..\..\obj\PACMAN_CUBERITE\src\file_functions.o ..\..\obj\PACMAN_CUBERITE\src\fly\extlibs\src\simplexnoise.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\Airplane.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\BoundingBox.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\Camera.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\CameraController.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\Controller.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\Debug\Box.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\FrameBuffer.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\Log.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\main.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\Model.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\ParticleData.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\ParticleEmitters.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\ParticleRenderer.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\ParticleSystem.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\ParticleUpdaters.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\Shader.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\ShadowMap.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\Sky.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\Sprite.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\Terrain.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\TerrainRenderer.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\TextureManager.o ..\..\obj\PACMAN_CUBERITE\src\fly\src\Utility.o ..\..\obj\PACMAN_CUBERITE\src\GetFileFromInternet.o ..\..\obj\PACMAN_CUBERITE\src\init.o ..\..\obj\PACMAN_CUBERITE\src\key_functions.o ..\..\obj\PACMAN_CUBERITE\src\main.o ..\..\obj\PACMAN_CUBERITE\src\make_black_transparant.o ..\..\obj\PACMAN_CUBERITE\src\map.o ..\..\obj\PACMAN_CUBERITE\src\maps.o ..\..\obj\PACMAN_CUBERITE\src\Maze.o ..\..\obj\PACMAN_CUBERITE\src\maze3d.o ..\..\obj\PACMAN_CUBERITE\src\maze_functions.o ..\..\obj\PACMAN_CUBERITE\src\MCA-NBT-EDIT.o ..\..\obj\PACMAN_CUBERITE\src\MCEditor\globals.o ..\..\obj\PACMAN_CUBERITE\src\MCEditor\MCACoder.o ..\..\obj\PACMAN_CUBERITE\src\MCEditor\MCEditor.o ..\..\obj\PACMAN_CUBERITE\src\MCEditor\NBTCoder.o ..\..\obj\PACMAN_CUBERITE\src\MCEditor\paint.o ..\..\obj\PACMAN_CUBERITE\src\MCEditor\test.o ..\..\obj\PACMAN_CUBERITE\src\MediaInfo.o ..\..\obj\PACMAN_CUBERITE\src\Minecraft.o ..\..\obj\PACMAN_CUBERITE\src\miniz.o ..\..\obj\PACMAN_CUBERITE\src\moviedemo.o ..\..\obj\PACMAN_CUBERITE\src\myzpipe.o ..\..\obj\PACMAN_CUBERITE\src\NBT.o ..\..\obj\PACMAN_CUBERITE\src\network.o ..\..\obj\PACMAN_CUBERITE\src\OBJ-Loader\e1_loadandprint.o ..\..\obj\PACMAN_CUBERITE\src\play.o ..\..\obj\PACMAN_CUBERITE\src\plotting.o ..\..\obj\PACMAN_CUBERITE\src\print_to_screen.o ..\..\obj\PACMAN_CUBERITE\src\recording.o ..\..\obj\PACMAN_CUBERITE\src\scanner.o ..\..\obj\PACMAN_CUBERITE\src\scripting.o ..\..\obj\PACMAN_CUBERITE\src\Shader.o ..\..\obj\PACMAN_CUBERITE\src\shaders.o ..\..\obj\PACMAN_CUBERITE\src\SimpleViewer\MeshLib\core\bmp\RgbImage.o ..\..\obj\PACMAN_CUBERITE\src\SimpleViewer\Viewer\view_mesh.o ..\..\obj\PACMAN_CUBERITE\src\stdafx.o ..\..\obj\PACMAN_CUBERITE\src\StreamSelector.o ..\..\obj\PACMAN_CUBERITE\src\TCP.o ..\..\obj\PACMAN_CUBERITE\src\text_functions.o ..\..\obj\PACMAN_CUBERITE\src\TPLL.o ..\..\obj\PACMAN_CUBERITE\src\UDP.o ..\..\obj\PACMAN_CUBERITE\src\UserInterface.o ..\..\obj\PACMAN_CUBERITE\src\viewer\ANGLES.o ..\..\obj\PACMAN_CUBERITE\src\viewer\area_data.o ..\..\obj\PACMAN_CUBERITE\src\viewer\area_data_amsterdam.o ..\..\obj\PACMAN_CUBERITE\src\viewer\rotate_around_point.o ..\..\obj\PACMAN_CUBERITE\src\viewer\rotje.o ..\..\obj\PACMAN_CUBERITE\src\viewer\trackball.o ..\..\obj\PACMAN_CUBERITE\src\viewer\viewer_my.o ..\..\obj\PACMAN_CUBERITE\src\VOXEL_TO_REGION.o ..\..\obj\PACMAN_CUBERITE\src\wierdo.o ..\..\obj\PACMAN_CUBERITE\src\winapi.o ..\..\obj\PACMAN_CUBERITE\src\WinMain.o ..\..\obj\PACMAN_CUBERITE\src\WUPPIE.o ..\..\obj\PACMAN_CUBERITE\src\xallocator.o ..\..\obj\PACMAN_CUBERITE\src\xalloctest.o  -m64 -static-libgcc -static-libstdc++ -fstack-protector -Wl,-u,vfscanf  -lm  lib\libsfml-graphics-s.a lib\libsfml-window-s.a lib\libsfml-audio-s.a lib\libsfml-system-s.a lib\libsfml-network-s.a lib\libsfml-main.a lib\glew32s.lib lib\libfreeglut_static.a lib\libglfw3.a lib\libglu32.a lib\libopengl32.a lib\libopenal32.a lib\libFLAC.a lib\libfreetype.a lib\libjpeg.a lib\libvorbisfile.a lib\libvorbis.a lib\libvorbisenc.a lib\libogg.a lib\libwinmm.a lib\libgdi32.a lib\libsfeMovie-s.a lib\libavdevice.a lib\libavformat.a lib\libavfilter.a lib\libavcodec.a lib\libswresample.a lib\libswscale.a lib\libavutil.a lib\libpsapi.a lib\libwsock32.a lib\libkernel32.a lib\libparser.a lib\libstdlib.a lib\libstdc++.a lib\libz.a lib\libiconv.a lib\libiphlpapi.a lib\libssp.a lib\libversion.a lib\cuberite\fmt\fmt\libfmt.a lib\cuberite\jsoncpp\src\lib_json\libjsoncpp.a lib\cuberite\libevent\lib\libevent_core.a lib\cuberite\libevent\lib\libevent_extra.a lib\cuberite\mbedtls\library\libmbedtls.a lib\cuberite\mbedtls\library\libmbedcrypto.a lib\cuberite\mbedtls\library\libmbedx509.a lib\cuberite\sqlite\libsqlite.a lib\cuberite\SQLiteCpp\libSQLiteCpp.a lib\cuberite\zlib\libzlib.a lib\cuberite\luaexpat\libluaexpat.a lib\cuberite\tolua++\libtolualib.a lib\cuberite\luaproxy\CMakeFiles\luaproxy.dir\objects.a lib\cuberite\expat\libexpat.a lib\cuberite\lua\CMakeFiles\luaexe.dir\objects.a lib\cuberite\liblua5.1.dll.a lib\cuberite\liblua51.dll.a lib\cuberite\lua\CMakeFiles\lua.dir\objects.a lib\libws2_32.a

2. Load .obj file '...'

Correct loading:
https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/tree/main/objects_LOW_VALUES

Loaded .obj file with low values, not adapted (of course) from objects_LOW_VALUES

-# of vertices  = 526338  # of normals   = 0  # of colors    = 526338  # of texcoords = 8  # of materials = 16  # of shapes    = 1

shapes[0].mesh.indices.size()=3158016

OBJECT MIN: X=     0.00000000000000000 Y=     0.00000000000000000 Z=     0.00000000000000000
OBJECT MAX: X=   512.00000000000000000 Y=     1.00000000000000000 Z=   512.00000000000000000
OBJECT DIF: X=   512.00000000000000000 Y=     1.00000000000000000 Z=   512.00000000000000000

t 342.000000 0.000000 176.000000 - 342.000000 0.000000 177.000000 - 341.000000 0.000000 177.000000
t 342.000000 0.000000 176.000000 - 341.000000 0.000000 177.000000 - 341.000000 0.000000 176.000000
t 341.000000 1.000000 177.000000 - 342.000000 1.000000 177.000000 - 342.000000 1.000000 176.000000
t 341.000000 1.000000 177.000000 - 342.000000 1.000000 176.000000 - 341.000000 1.000000 176.000000
t 342.000000 0.000000 161.000000 - 342.000000 0.000000 162.000000 - 341.000000 0.000000 162.000000
t 342.000000 0.000000 161.000000 - 341.000000 0.000000 162.000000 - 341.000000 0.000000 161.000000
t 341.000000 1.000000 162.000000 - 342.000000 1.000000 162.000000 - 342.000000 1.000000 161.000000
t 341.000000 1.000000 162.000000 - 342.000000 1.000000 161.000000 - 341.000000 1.000000 161.000000
t 342.000000 0.000000 162.000000 - 342.000000 0.000000 163.000000 - 341.000000 0.000000 163.000000
t 342.000000 0.000000 162.000000 - 341.000000 0.000000 163.000000 - 341.000000 0.000000 162.000000
t 341.000000 1.000000 163.000000 - 342.000000 1.000000 163.000000 - 342.000000 1.000000 162.000000
t 341.000000 1.000000 163.000000 - 342.000000 1.000000 162.000000 - 341.000000 1.000000 162.000000
t 342.000000 0.000000 163.000000 - 342.000000 0.000000 164.000000 - 341.000000 0.000000 164.000000
t 342.000000 0.000000 163.000000 - 341.000000 0.000000 164.000000 - 341.000000 0.000000 163.000000
t 341.000000 1.000000 164.000000 - 342.000000 1.000000 164.000000 - 342.000000 1.000000 163.000000
t 341.000000 1.000000 164.000000 - 342.000000 1.000000 163.000000 - 341.000000 1.000000 163.000000
t 342.000000 0.000000 164.000000 - 342.000000 0.000000 165.000000 - 341.000000 0.000000 165.000000
t 342.000000 0.000000 164.000000 - 341.000000 0.000000 165.000000 - 341.000000 0.000000 164.000000
(etc.) (correct)

Wrong loading:
https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/tree/main/objects_HIGH_VALUES

Loaded with high values, (offsets X=+14336 Y=0 Z=+9216) from directory objects_HIGH_VALUES
(Edited (missing))
Then VERTICES adapted after loading with:

int n_v=(int)(attrib.vertices.size()) / 3;
    for (size_t v = 0; v < n_v; v++) {
	    attrib.vertices[3 * v + 0]-=14336;
	    attrib.vertices[3 * v + 1]-=0;
	    attrib.vertices[3 * v + 2]-=9216;
    }
To compare when loaded without offsets and not adapted. (FILE FACES_LOW_VALUES.TXT)
(https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/blob/main/FACES_LOW_VALUES.zip)

-# of vertices  = 526338  # of normals   = 0  # of colors    = 526338  # of texcoords = 8  # of materials = 16  # of shapes    = 1

shapes[0].mesh.indices.size()=2749740

OBJECT MIN: X=     0.00000000000000000 Y=     0.00000000000000000 Z=     0.00000000000000000
OBJECT MAX: X=   512.00000000000000000 Y=     1.00000000000000000 Z=   512.00000000000000000
OBJECT DIF: X=   512.00000000000000000 Y=     1.00000000000000000 Z=   512.00000000000000000

t 342.000000 0.000000 176.000000 - 342.000000 0.000000 177.000000 - 341.000000 0.000000 177.000000
t 342.000000 0.000000 176.000000 - 341.000000 0.000000 177.000000 - 341.000000 0.000000 176.000000
t 341.000000 1.000000 177.000000 - 342.000000 1.000000 177.000000 - 342.000000 1.000000 176.000000
t 341.000000 1.000000 177.000000 - 342.000000 1.000000 176.000000 - 341.000000 1.000000 176.000000
t 342.000000 0.000000 161.000000 - 342.000000 0.000000 162.000000 - 341.000000 0.000000 162.000000
t 342.000000 0.000000 161.000000 - 341.000000 0.000000 162.000000 - 341.000000 0.000000 161.000000
t 341.000000 1.000000 162.000000 - 342.000000 1.000000 162.000000 - 342.000000 1.000000 161.000000
t 341.000000 1.000000 162.000000 - 342.000000 1.000000 161.000000 - 341.000000 1.000000 161.000000
t 342.000000 0.000000 162.000000 - 342.000000 0.000000 163.000000 - 341.000000 0.000000 163.000000
t 342.000000 0.000000 162.000000 - 341.000000 0.000000 163.000000 - 341.000000 0.000000 162.000000
t 341.000000 1.000000 163.000000 - 342.000000 1.000000 163.000000 - 342.000000 1.000000 162.000000
t 341.000000 1.000000 163.000000 - 342.000000 1.000000 162.000000 - 341.000000 1.000000 162.000000
t 342.000000 0.000000 163.000000 - 342.000000 0.000000 164.000000 - 341.000000 0.000000 164.000000
t 342.000000 0.000000 163.000000 - 341.000000 0.000000 164.000000 - 341.000000 0.000000 163.000000
t 341.000000 1.000000 164.000000 - 342.000000 1.000000 164.000000 - 342.000000 1.000000 163.000000
t 341.000000 1.000000 164.000000 - 342.000000 1.000000 163.000000 - 341.000000 1.000000 163.000000
missing
missing
missing
missing
t 342.000000 0.000000 165.000000 - 342.000000 0.000000 166.000000 - 341.000000 0.000000 166.000000
t 342.000000 0.000000 165.000000 - 341.000000 0.000000 166.000000 - 341.000000 0.000000 165.000000
t 341.000000 1.000000 166.000000 - 342.000000 1.000000 166.000000 - 342.000000 1.000000 165.000000
t 341.000000 1.000000 166.000000 - 342.000000 1.000000 165.000000 - 341.000000 1.000000 165.000000
t 342.000000 0.000000 166.000000 - 342.000000 0.000000 167.000000 - 341.000000 0.000000 167.000000
t 342.000000 0.000000 166.000000 - 341.000000 0.000000 167.000000 - 341.000000 0.000000 166.000000
(etc.)(missing faces)
Without adapting after loading (orig.):

Loaded .obj file with high values, not adapted from directory objects_HIGH_VALUES
(https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/blob/main/FACES_HIGH_VALUES.zip)
(Edited (missing))

-# of vertices  = 526338  # of normals   = 0  # of colors    = 526338  # of texcoords = 8  # of materials = 16  # of shapes    = 1

shapes[0].mesh.indices.size()=2749740

OBJECT MIN: X= 14336.00000000000000000 Y=     0.00000000000000000 Z=  9216.00000000000000000
OBJECT MAX: X= 14848.00000000000000000 Y=     1.00000000000000000 Z=  9728.00000000000000000
OBJECT DIF: X=   512.00000000000000000 Y=     1.00000000000000000 Z=   512.00000000000000000

t 14678.000000 0.000000 9392.000000 - 14678.000000 0.000000 9393.000000 - 14677.000000 0.000000 9393.000000
t 14678.000000 0.000000 9392.000000 - 14677.000000 0.000000 9393.000000 - 14677.000000 0.000000 9392.000000
t 14677.000000 1.000000 9393.000000 - 14678.000000 1.000000 9393.000000 - 14678.000000 1.000000 9392.000000
t 14677.000000 1.000000 9393.000000 - 14678.000000 1.000000 9392.000000 - 14677.000000 1.000000 9392.000000
t 14678.000000 0.000000 9377.000000 - 14678.000000 0.000000 9378.000000 - 14677.000000 0.000000 9378.000000
t 14678.000000 0.000000 9377.000000 - 14677.000000 0.000000 9378.000000 - 14677.000000 0.000000 9377.000000
t 14677.000000 1.000000 9378.000000 - 14678.000000 1.000000 9378.000000 - 14678.000000 1.000000 9377.000000
t 14677.000000 1.000000 9378.000000 - 14678.000000 1.000000 9377.000000 - 14677.000000 1.000000 9377.000000
t 14678.000000 0.000000 9378.000000 - 14678.000000 0.000000 9379.000000 - 14677.000000 0.000000 9379.000000
t 14678.000000 0.000000 9378.000000 - 14677.000000 0.000000 9379.000000 - 14677.000000 0.000000 9378.000000
t 14677.000000 1.000000 9379.000000 - 14678.000000 1.000000 9379.000000 - 14678.000000 1.000000 9378.000000
t 14677.000000 1.000000 9379.000000 - 14678.000000 1.000000 9378.000000 - 14677.000000 1.000000 9378.000000
t 14678.000000 0.000000 9379.000000 - 14678.000000 0.000000 9380.000000 - 14677.000000 0.000000 9380.000000
t 14678.000000 0.000000 9379.000000 - 14677.000000 0.000000 9380.000000 - 14677.000000 0.000000 9379.000000
t 14677.000000 1.000000 9380.000000 - 14678.000000 1.000000 9380.000000 - 14678.000000 1.000000 9379.000000
t 14677.000000 1.000000 9380.000000 - 14678.000000 1.000000 9379.000000 - 14677.000000 1.000000 9379.000000
missing
missing
missing
missing
t 14678.000000 0.000000 9381.000000 - 14678.000000 0.000000 9382.000000 - 14677.000000 0.000000 9382.000000
t 14678.000000 0.000000 9381.000000 - 14677.000000 0.000000 9382.000000 - 14677.000000 0.000000 9381.000000
t 14677.000000 1.000000 9382.000000 - 14678.000000 1.000000 9382.000000 - 14678.000000 1.000000 9381.000000
t 14677.000000 1.000000 9382.000000 - 14678.000000 1.000000 9381.000000 - 14677.000000 1.000000 9381.000000
t 14678.000000 0.000000 9382.000000 - 14678.000000 0.000000 9383.000000 - 14677.000000 0.000000 9383.000000
t 14678.000000 0.000000 9382.000000 - 14677.000000 0.000000 9383.000000 - 14677.000000 0.000000 9382.000000
(etc.)(missing faces)

3. See error

Correct:
https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/blob/main/FACES_LOW_VALUES.zip
https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/blob/main/LOW_VALUES_TINY_OBJ.JPG

Wrong:
https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/blob/main/FACES_HIGH_VALUES.zip
and/or
https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/blob/main/FACES_HIGH_VALUES_ADAPTED.zip
https://github.com/HakkaTjakka/My-error-report-on-tiny_obj_loader.h/blob/main/HIGH_VALUES_TINY_OBJ.JPG

Please attach minimal and reproducible files(source codes, .obj/.mtl files, etc)
(Follow links, large size/zipped)

**Expected behavior**
No missing faces?

**Environment**
 - TinyObjLoader version: https://github.com/tinyobjloader/tinyobjloader.git
 - OS: Windows 10 pro 64bit
 - Compiler:  x86_64-w64-mingw32

I hope this is better?

**Comment by syoyo** [comment]
You should describe your issue more clear manner and attach **minimal** and **reproducible** .obj/.mtl files

**Comment by HakkaTjakka** [comment]
Ok.
