### ISSUE TITLE
Integrate mapbox earcut.hpp for robust triangulation.

### ISSUE THREAD

**Issue by syoyo** [tinyobjloader/tinyobjloader#297]
**Describe the issue**

TinyObjLoader's triangulation code is not robust(and/or may contains a bug).

**To Reproduce**

Issue 295 is triggered by triangulation code bug:
 
https://github.com/tinyobjloader/tinyobjloader/issues/295

**Expected behavior**

Its highly recommended to implement robust triangulation algorithm.
Writing it from a scratch would be painful, so possible candidate is integrating existing codes  `mapbox/earcut.hpp` 

https://github.com/mapbox/earcut.hpp

**Limitation**

`mapbox/earcut.hpp` is written in C++11, so requires C++11 compiler.

**Environment**
 - TinyObjLoader version: `main`(v2.0 RC)

**Comment by syoyo** [comment]
PR is here https://github.com/tinyobjloader/tinyobjloader/pull/298

**Comment by syoyo** [comment]
Closed via PR #298

**Comment by meshula** [comment]
Nice!
