### ISSUE TITLE
Shapes contain multiple smooth group id's when running computeSmoothingNormals() in viewer.cpp

### ISSUE THREAD

**Issue by bc-nine** [tinyobjloader/tinyobjloader#323]
Based on #29 I was expecting to find code that partitioned an obj with multiple smooth groups into separate shapes, where each shape has a single smooth group id, so that the computeSmoothingNormals() function in viewer.cpp would work properly.

However, I don't see that happening anywhere, so in the example, computeSmoothingNormals() will be triggered if a shape has *any* > 0 smooth group ids, but since the shapes aren't partitioned into separate bins per smooth group id, all the smooth groups in a shape containing multiple smooth group ids are essentially treated as a single large smooth group, which isn't correct. I'm confused because issue #29 specifically mentions doing this, and yet I don't see where it's done anywhere in the code.

**Comment by syoyo** [comment]
@bc-nine Please attach minimal and reproducible .obj  file

**Comment by bc-nine** [comment]
Here's a minimal(ish) obj, two triangles, each in its own smooth group:

`
v 0.000000 0.000000 0.000000
v 1.000000 0.000000 -1.000000
v 0.000000 1.000000 0.000000
v -1.000000 0.000000 -1.000000
vt 0.500000 0.000000
vt 1.000000 0.000000
vt 1.000000 1.000000
vt 0.000000 0.000000

s 1
f 1/1 2/2 3/3

s 2
f 1/1 3/3 4/4
`

Running the viewer app in the examples folder produces 

![image](https://user-images.githubusercontent.com/66544272/143507647-e7f76cdb-fdce-499d-8167-9df4737906fc.png)

but should produce

![image](https://user-images.githubusercontent.com/66544272/143507694-feb0c10b-827a-4972-bb72-4f483c19f4fb.png)

It's a bit complicated in general to handle this properly, as you need to generate new vertices to get sharp edges. I can submit a PR for this, just wanted to confirm the issue first. As a bit of background, some obj files, for example the architectural model packs from Evermotion, use smooth groups instead of explicit vertex normals, presumably for smaller file sizes, which means vertex normals must be reconstructed based on these groups.

**Comment by syoyo** [comment]
@bc-nine Thanks for the .obj. 


> computeSmoothingNormals() will be triggered if a shape has any > 0 smooth group ids

https://github.com/tinyobjloader/tinyobjloader/blob/097ad6a826336a76e42a27e6e531da7dbdf3fd01/examples/viewer/viewer.cc#L422

Oh, yes. There is no use of smoothingGroup ID when computing shading(vertex) normal in `viewer` example(something may be mentioned in #29, but not implemented)
 
PR of computing shading normal by looking up smoothingGroup ID is much appreciated!
(FYI `tiny_obj_loader.h` itself does not compute (smoothing) normals)

**Comment by bc-nine** [comment]
Closing this, as pr #324 / #325 has been merged (thank you!)
