### ISSUE TITLE
Using vector.emplace_back and reserve() to improve profermance?

### ISSUE THREAD

**Issue by dreakWang** [tinyobjloader/tinyobjloader#328]
Thanks for your contribution!. It saves a lot of time for our project. But may I ask whether you thought about using vector.emplace_back instead of vector.push_back and using vector.reserve() before inserting elements to improve the performance? Thanks!

**Comment by syoyo** [comment]
tinyobjloader supports C++03, so no C++11 feature.

In the future release, we may raise minimum C++ version requirement to C++11
