### ISSUE TITLE
How to package tinyobjloader?

### ISSUE THREAD

**Issue by bernhardmgruber** [tinyobjloader/tinyobjloader#337]
I am currently updating the vcpkg port of tinyobjloader and it was pointed out that the `TINYOBJLOADER_USE_DOUBLE` feature is ABI changing. See discussion here: https://github.com/microsoft/vcpkg/pull/25055#issuecomment-1150988939

Now I wonder how tinyobjloader should be packaged correctly (I am not experienced in package management). Currently, vcpkg distributes the `tinyobjloader.h` and a static library compiled from `tinyobjloader.cc`, which is what the cmake build of tinyobjloader does by default. This static library can only be built for `float` *or* `double`. This way, users also do not need to define `TINYOBJLOADER_IMPLEMENTATION` in any of their files, because that is already part of the static library.

I have seen you had a previous discussion on replacing `TINYOBJLOADER_USE_DOUBLE` by templates: https://github.com/tinyobjloader/tinyobjloader/issues/233. This could be a long-term solution.

Other options I could think of are:

* always building tinyobjloader for `float`.
* change the vcpkg port to only distribute the header file, requiring users to define `TINYOBJLOADER_IMPLEMENTATION` in one of their files, and optionally `TINYOBJLOADER_USE_DOUBLE` for their project.

Could you please provide me with guidance on how to proceed? Thank you!

Disclaimer: I am not associated with Microsoft, I am just a random PhD student using vcpkg :)

**Comment by syoyo** [comment]
We don't recommend packaging tinyobjloader, since its a header-only library.

If you still wanted to package vcpkg, use `float` build or distribute only the header file for a while. 
`TINYOBJLOADER_USE_DOUBLE` is primarily for HPC people and Python binding(Python uses double as a `float` type)

`TINYOBJLOADER_USE_DOUBLE` ifdef is an annoying problem. Best way is to introduce templated types or provide new API for double precision as you seen in issue #233. Your PR is much appreciated!

**Comment by bernhardmgruber** [comment]
> We don't recommend packaging tinyobjloader, since its a header-only library.

It's also great to install and update header only libraries via a package manager.

For vcpkg, we now chose to patch `tinyobjloader.h` and replace the `#ifdef TINYOBJLOADER_USE_DOUBLE` either by `#if 1` or `#if 0`, depending on how the user installed it. This way, this decision is kept for all downstream dependencies or projects consuming the package.
