### ISSUE TITLE
LoadObj fails to load materials while reader object succeeds

### ISSUE THREAD

**Issue by jpbucsd** [tinyobjloader/tinyobjloader#339]
**Describe the issue**
tinyobj::LoadObj() fails to load materials from an object while reader.ParseFromFile() operates as expected.

**To Reproduce**
Using the following code:

```
#define TINYOBJLOADER_IMPLEMENTATION
#include "tiny_obj_loader.h"
...
//load model contained at MODEL_PATH (std::string) through reader
tinyobj::ObjReader reader;
tinyobj::ObjReaderConfig reader_config;
if (!reader.ParseFromFile(MODEL_PATH.c_str(), reader_config)) {
     if (!reader.Error().empty()) {
         std::cerr << "TinyObjReader: " << reader.Error();
     }
     exit(1);
}
if (!reader.Warning().empty()) {
    std::cout << "TinyObjReader: " << reader.Warning();
}
auto& attrib2 = reader.GetAttrib();
auto& shapes2 = reader.GetShapes();
auto& materials2 = reader.GetMaterials();
std::cout << "number of materials through reader: " << materials2.size() << std::endl;

//load model contained at MODEL_PATH (std::string) through LoadObj
tinyobj::attrib_t attrib;
std::vector<tinyobj::shape_t> shapes;
std::vector<tinyobj::material_t> materials;
std::string warn, err;
if (!tinyobj::LoadObj(&attrib, &shapes, &materials, &warn, &err, MODEL_PATH.c_str())) {
    throw std::runtime_error(warn + err);
}
std::cout << "number of materials through LoadObj: " << materials.size() << std::endl;
```
[mats.zip](https://github.com/tinyobjloader/tinyobjloader/files/9035994/mats.zip)
using the attached obj file at MODEL_PATH, the following output is obtained:
number of materials through reader: 2
number of materials through LoadObj: 0

**Expected behavior**
I expect both loaders to load 2 materials

**Environment**
 - TinyObjLoader version 2.0.0
 - OS: Windows
 - Compiler: Visual Studio 2022

**Comment by syoyo** [comment]
In `LoadObj`, .mtl is searched from working directory if you don't supply search path for .mtl to `mtl_basedir` 

https://github.com/tinyobjloader/tinyobjloader/blob/03a2f3a46615da7da641c170b8823b3e0fb63110/tiny_obj_loader.h#L596

`LoadObj` is deprecated API and not recommended to use. You are recommended to use `ObjReader` API
