### ISSUE TITLE
Normal indices with a value of zero

### ISSUE THREAD

**Issue by Trider12** [tinyobjloader/tinyobjloader#348]
**Describe the issue**
I know that this a strange request, but is it possible to support invalid (i.e. zero) normal indices? Currently I get the following error:
```
Failed parse `f' line(e.g. zero value for face index. line 70537.)
```
The problematic line looks like this:
```
f 22979/21114/0 22978/21108/3845 23110/21108/3853 23345/21115/3852 23346/21324/4037 23108/21323/3901
```
And it's not the only such line. In fact, it seems all the hexagons in this file have this issue. The file is generated by Cinema 4D, so it seems that their exporter is bugged (I couldn't find any easy way of reporting this issue to them).

**To Reproduce**
Unfortunately, I can't provide a sample .obj file due to the licensing.

**Expected behavior**
It would be nice if instead of aborting, the library provided invalid normal indices for such vertices, so I could handle these values in my code. Thanks.
```cpp
struct index_t {
  int vertex_index;
  int normal_index; // -1 here, for example
  int texcoord_index;
};
```

**Comment by syoyo** [comment]
http://paulbourke.net/dataformats/obj/

The spec say nothing when normal/texcoord index is zero(even vertex, but at least it should be an error having zero for vertex index)

How Blender and meshlab handles such .obj data?

**Comment by Trider12** [comment]
> How Blender and meshlab handles such .obj data?

I'll test that and come back with the results.

**Comment by Trider12** [comment]
I tested the model in Blender and CAD Assistant (which uses [Open Cascade](https://github.com/Open-Cascade-SAS/OCCT)) and both of them imported the model fine, but the faces with the zeroed indices had incorrect shading (like the normals for that face or that particular vertex were inverted).

**Comment by syoyo** [comment]
@Trider12 Thanks! So Blender and other tools seems use zero normal value(`0, 0, 0`) or maybe `0, 0, 1` for invalid normal index.

TinyObjLoader's solution would be

- Set -1(indicates invalid) when `f` normal index(and also texcoord index) is zero
  - App need to handle it correctly instead
- Report warning
 
PR is much appreciated!
