### ISSUE TITLE
All vertex color data is (1,1,1)

### ISSUE THREAD

**Issue by CharlieW112** [tinyobjloader/tinyobjloader#351]
When loading the default "cornell_box.obj" and "cornell_box.mtl" files using the exemplar object-oriented code from the README all vertex color data is returned as (1, 1, 1). The code is a straight copy and paste of yours with NO modification whatsoever other than one line to print the color data to the terminal. This issue occurs on multiple different obj and mtl files and no errors are outputted in either case. All other data from the mesh is loaded perfectly fine.

There should be multiple different vertex colors within the mesh, as it is the example "cornell_box.mtl" file.

 - TinyObjLoader 1.06
 - OS: Windows 11
 - Compiler g++ 12.2
[tinyobjloaderTest.zip](https://github.com/tinyobjloader/tinyobjloader/files/9963936/tinyobjloaderTest.zip)

**Comment by syoyo** [comment]
You need to supply vertex color info to `v` 

https://github.com/tinyobjloader/tinyobjloader/blob/release/models/cube-vertexcol.obj

https://blender.stackexchange.com/questions/31997/how-can-i-get-vertex-painted-obj-files-to-import-into-blender
