### ISSUE TITLE
Adding my project to Use Case section

### ISSUE THREAD

**Issue by MohitSethi99** [tinyobjloader/tinyobjloader#353]
I'm using tinyobjloader in my game engine: https://github.com/MohitSethi99/ArcGameEngine
Can you please add it to the Use Case section?

**Comment by syoyo** [comment]
Yeah! Could you please send a PR of adding your engine to README.md?

**Comment by syoyo** [comment]
Closed via https://github.com/tinyobjloader/tinyobjloader/pull/354
