### ISSUE TITLE
mtllib filename with spaces

### ISSUE THREAD

**Issue by mgerhardy** [tinyobjloader/tinyobjloader#355]
**Describe the issue**
If the `mtllib` line contains a space character in the filename, the parsing is not working properly

**Environment**
 - TinyObjLoader version: 2f947710aeedea2089ade2b62ef669521d90f2ef
 - OS: Linux
 - Compiler  clang version 14.0.6

This hack fixes the issue - not sure why the splitting is done here.

```diff
diff --git a/src/modules/voxelformat/external/tiny_obj_loader.h b/src/modules/voxelformat/external/tiny_obj_loader.h
index d8e7c4194..3cd36f5d2 100644
--- a/src/modules/voxelformat/external/tiny_obj_loader.h
+++ b/src/modules/voxelformat/external/tiny_obj_loader.h
@@ -2836,7 +2836,8 @@ bool LoadObj(attrib_t *attrib, std::vector<shape_t> *shapes,
         token += 7;
 
         std::vector<std::string> filenames;
-        SplitString(std::string(token), ' ', '\\', filenames);
+        //SplitString(std::string(token), ' ', '\\', filenames);
+        filenames.push_back(token);
 
         if (filenames.empty()) {
           if (warn) {
```

The obj file was exported by blender 2.79 and the mtllib line looked like this:
```
# Blender v2.79 (sub 0) OBJ File: ''
# www.blender.org
mtllib foo bar.mtl
```

**Comment by syoyo** [comment]
`mtllib` can specify multiple filenames by spaces https://github.com/tinyobjloader/tinyobjloader/issues/112

Possible solution will be escape whitespaces in filename.

Also, Blender 2.79 is too old, you should not use it.

**Comment by mgerhardy** [comment]
thanks a lot
