### ISSUE TITLE
I am getting texcoord_index = -1 for some models?

### ISSUE THREAD

**Issue by ForceConstant** [tinyobjloader/tinyobjloader#359]
So I have exported a few models from Blender, and some work in my code that uses u_tiny_loader.h , and some dont. I have tracked it town to texcoord_index, where on the bad ones texcoord_index ends up being -1, and the good one is a valid index. Both good and bad models were exported with the same version of blender, and have the same texture, mtl file. What should I be looking at for a difference and how to fix? In the attached file, Bathy2.obj works, but Bathy.obj doesn't.

[Bathy.zip](https://github.com/tinyobjloader/tinyobjloader/files/10561428/Bathy.zip)

**Comment by syoyo** [comment]
Bathy.obj does not have vertex texture coordinate index for some `f`s,  so its filled with -1(invalid)

```
...
f 1100//2030 1089//2030 1064//2030
```

You need to check if vt_index is not -1 when setting up texture coordinates
 https://github.com/tinyobjloader/tinyobjloader/blob/0fc802cf468d23b9d205890b76b268f61b948e6d/examples/viewer/viewer.cc#L621

**Comment by ForceConstant** [comment]
@syoyo Good catch, I didn't see that missing number in the slashes. Any ideas why Blender would export file like this in some cases?
