### ISSUE TITLE
I just need index buffer

### ISSUE THREAD

**Issue by coderboyisongithub** [tinyobjloader/tinyobjloader#360]
I am using your library and want to extract index buffer here is the following code I am using 
`auto& attrib = reader.GetAttrib();
	auto& shapes = reader.GetShapes();
	auto& materials = reader.GetMaterials();
	  

	//allocating vertex array..
	float* model_vertex = (float*)malloc(sizeof(float) * attrib.vertices.size());
	int i = 0;
	for each (float vtx in attrib.vertices)
	{

		model_vertex[i] = vtx;
		i++;
	}

	//allocating index array
		 unsigned int* index = (unsigned int*)malloc(sizeof(unsigned int) * shapes[0].mesh.indices.size()*3);

		std::cout<<shapes[0].mesh.indices.size()<<"\n"<< attrib.vertices.size();
		
		
	for (int index_count = 0; index_count < shapes[0].mesh.indices.size(); index_count++)
	{
		tinyobj::index_t ind_x = shapes[0].mesh.indices[index_count];
		index[index_count] = ind_x.vertex_index;

		index_count++;
		 ind_x = shapes[0].mesh.indices[index_count];
		index[index_count] = ind_x.vertex_index;

		index_count++;
		ind_x = shapes[0].mesh.indices[index_count];
		index[index_count] = ind_x.vertex_index;
		
	}
`

But while rendering I am getting weird shape...I am using drawelements with GL_TRIANGLES

**Comment by syoyo** [comment]
https://github.com/tinyobjloader/tinyobjloader#data-format
