### ISSUE TITLE
Facets with > 255 vertices

### ISSUE THREAD

**Issue by jdumas** [tinyobjloader/tinyobjloader#372]
Hi,

Is there any reason to restrict the number of vertices per facet to be <255?
https://github.com/tinyobjloader/tinyobjloader/blob/ee45fb41db95bf9563f2a41bc63adfa18475c2ee/tiny_obj_loader.h#L356

Using a `int` rather than a `char` here would allow me to load complex polygonal facets with potentially more than 255 vertices. Even bumping it to a 16bit int would help. I don't imagine it would hurt performance too much, but could we at least it a configurable option?

**Comment by syoyo** [comment]
There is no strong reason to use `uchar`. Simply I thought 255 is enough for the number of vertices per facet.

We can bump it to `uint`.  PR is much appreciated!

**Comment by jdumas** [comment]
Thanks! I created a PR in #375
