### ISSUE TITLE
New release 1.0.7?

### ISSUE THREAD

**Issue by Vertexwahn** [tinyobjloader/tinyobjloader#373]
The last release is quite old (2019) - would it possible to do an up to date release - e.g. "1.0.7"?

**Comment by syoyo** [comment]
https://github.com/tinyobjloader/tinyobjloader/releases/tag/v2.0-rc1

We've been still working in v2.0 Release Candidate(for 4~5 years!)

> Since tinyobjloader is a single file, header-only library, we encourage grab a recent file from release branch(which is been stable and very near to version v2.0(API changes still may happen)).

Please use `release`(default) git branch, which is  stable enough.
