### ISSUE TITLE
How to get the material names without a .mtl?

### ISSUE THREAD

**Issue by wxfred** [tinyobjloader/tinyobjloader#374]
**Describe the issue**
My model dosen't have a .mtl file, but I need to get the material name for each face. How can I do that?
I tried ObjReader::ParseFromFile, but the size of materials is 0, while there are 8 `usemtl` in the .obj file.

**Comment by syoyo** [comment]
I think you can use Load API with  Mtl callback. 

https://github.com/tinyobjloader/tinyobjloader/blob/ee45fb41db95bf9563f2a41bc63adfa18475c2ee/tiny_obj_loader.h#L626
