### ISSUE TITLE
incorrect face indexs for pentagon f 1/1/1 2/2/1 3/3/1 4/4/1 5/5/1 

### ISSUE THREAD

**Issue by jesusmontera** [tinyobjloader/tinyobjloader#382]
Hello, when tiny reads this line from an .obj
 f 1/1/1 2/2/1 3/3/1 4/4/1 5/5/1  the parse result with this:
```
idxs = shapes[0].mesh.indices
for i in idxs:
    print(i.vertex_index+1, i.texcoord_index+1, i.normal_index+1)

is: 
1 1 1
2 2 1
3 3 1
1 1 1
3 3 1
4 4 1
1 1 1
4 4 1
5 5 1
witch are 9 coordinates (v-vt-vn) and the files f described a pentagon of 5 coordinates (v-vt-vn).

**Comment by syoyo** [comment]
You should provide minimal & reproducible code

**Comment by jesusmontera** [comment]
the file is a 70 MB city, that is in this format:

> g Mesh2 Group3 Group2 Component_39_1 Model
> 
> usemtl M_94_20Statue_20of_20Liberty
> v -37875.7 118.495 76194.8
> vt 0.248282 -9.98293e-012
> vn -0.208256 1.9753e-013 0.978074
> v -37093.8 118.495 76361.3
> vt 0.504888 2.08592e-011
> v -37093.8 402.225 76361.3
> vt 0.504888 0.0497708
> v -37875.7 402.225 76194.8
> vt 0.248282 0.0497708
> f 6/6/2 7/7/2 8/8/2 9/9/2 
> 
> vt 0.0618633 8.66042e-012
> vn -0.970936 -3.32034e-012 -0.239337
> v -37280.2 118.495 77117.7
> vt 0.413593 1.92578e-011
> v -37280.2 402.225 77117.7
> vt 0.413593 0.0497708
> vt 0.0618633 0.0497708
> f 7/10/3 10/11/3 11/12/3 8/13/3 

As you each  "f" line describe a poligon, with a variable number length of triplets (v vt vn). Is this example case are 4 but can be 5, or more. 
Also if I need to render a polygon I can't do it because   _shapes[1].mesh.indices_ include all faces from a group "g", and one face is one poligon.
