### ISSUE TITLE
obj-parsing fails if a comment is at the end of a line of a definition with variable number of elements to read.

### ISSUE THREAD

**Issue by scschaefer** [tinyobjloader/tinyobjloader#389]
**Describe the issue**
The parser fails and stops parsing if a comment is at the end of a line defining an element with a variable number of possible elements following the token. For example, when defining a line like `l 1 3 # First line`, it's unknown how many vertex indices follow after the `l`. The while loop condition only looks for new line characters. Subsequently, the parser fails when it encounters the `#` character.

**To Reproduce**
Steps to reproduce the behaviour:
1. Compile TinyObjLoader
2. Load the .obj-file in the attached .zip-archive via ParseFromFile: [linien.zip](https://github.com/user-attachments/files/17869141/linien.zip)
4. See error: Failed to parse `l' line (e.g. a zero value for vertex index. Line 43).

For convenience, try this example project: 
[tiny_obj_loader_parser_bug.zip](https://github.com/user-attachments/files/17869596/tiny_obj_loader_parser_bug.zip)

**Remarks**
This bug only applies to tokens that have a variable number of elements:
- vw (skin weight)
- l (line)
- p (points)
- f (face)
- g (group)

**Expected behaviour**
The parser should stop parsing a line once it reaches the comment character `#`.

**Environment**
 - TinyObjLoader version: The latest version of tiny_obj_loader.h (commit 5cd3842f)
 - OS: Windows 10 x64
 - Compiler: MSVC 17.10.9 with C++20 support enabled
 - Other environment: N/A

**Comment by syoyo** [comment]
Thanks! Confirmed the issue with `loader_example`

```
$ ./loader_example linien.obj
WARN: A zero value index found (will have a value of -1 for normal and tex indices. Line 43).

ERR: Failed to parse `l' line (e.g. a zero value for vertex index. Line 43).
...
```

https://github.com/tinyobjloader/tinyobjloader/blob/5cd3842fdca3b06cc993801cff1825fc6d999068/tiny_obj_loader.h#L2752

We need to take into account of '#' in the loop.  Possible fix is

```
while (!IS_NEW_LINE(token[0])) {
  if (token[0] == '#') {
    continue;
  }
  ...
}
```

**Comment by scschaefer** [comment]
Awesome, thanks for the feedback.
I'm currently working on a pull requests, if that's all right? 🙂

**Comment by syoyo** [comment]
Thanks for the PR! Let me give some time to review the PR.
